Dev
RaymondBalise/rUM pull request #56
Opened 2024-10-30 20:54 UTC by kyleGrealis

- updated gist path for `.gitignore`
- silenced console output for downloading files and returning "[1] TRUE" when creating projects
- added `README.md` template for projects
- moved `@importFrom` to `R/rUM-package.R` to centralize dependencies
- added `write_scss()` function
- added `write_scss()` inside `make_project()` to add during project creation

2024-10-31 20:42 UTC, kyleGrealis commented
- updated PR to remove external gist downloads ([issue #57](https://github.com/RaymondBalise/rUM/issues/57))
- added DATED_PROGRESS_NOTES.md template & written to .Rbuildignore
- passed `check()` with no warnings, notes, errors

2024-11-06 22:47 UTC, kyleGrealis commented
needed to modify my original downloading of package internal gists to use `system.file()` or the package fails to write these to new projects

2024-11-07 19:31 UTC, RaymondBalise requested changes

2024-11-07 19:31 UTC, RaymondBalise commented on R/write_scss.R
> +#' would like to go down a rabbit hole:
This will not translate well for non-english speakers

2024-11-07 19:31 UTC, RaymondBalise commented on inst/old/analysis_1_0_2_9001.Rmd
I am not sure the _9001 files are the latest.  We should do a diff

2024-12-12 14:27 UTC, RaymondBalise requested changes
Update the news using my note

2024-12-12 14:27 UTC, RaymondBalise commented on NEWS.md
> +
## Breaking changes
  + None

## New features

+ added write_scss() function
+ added README.md template for projects

## Minor improvements and fixes

+ updated gist path for .gitignore
+ silenced console output for downloading files and returning "[1] TRUE" when creating projects
+ moved @importFrom to R/rUM-package.R to centralize dependencies
+ added write_scss() inside make_project() to add during project creation
+ moved paper templates from GitHub gists into the project inst/gists folder
+ moved old paper templates to inst/old

2024-12-12 14:36 UTC, RaymondBalise approved these changes

2024-12-12 14:36 UTC, merged