Dev2
RaymondBalise/rUM pull request #59
Opened 2024-11-08 16:39 UTC by kyleGrealis

removing external RUN_ME_FIRST.R and automating all the tasks with project building

2024-12-02 18:30 UTC, RaymondBalise requested changes

2024-12-02 18:30 UTC, RaymondBalise commented on NEWS.md
> +
This will need details

2024-12-02 18:30 UTC, RaymondBalise commented on R/write_scss.R
> +    links <- glue::glue(
should this be verbose = TRUE

2024-12-02 18:30 UTC, RaymondBalise commented on R/write_scss.R
> +#' Create a Quarto SCSS file
Add comment/vignette to say this is useful for adding in a second style sheet by setting the name to something else.

2024-12-02 18:30 UTC, RaymondBalise commented on inst/old/analysis_1_0_2_9001.Rmd
remove /old folder if all is good before CRAN release

2024-12-02 18:30 UTC, RaymondBalise commented on NEWS.md
> ++ Added custom.scss to non-package Quarto projects
add new function name and what it does

2024-12-02 18:30 UTC, RaymondBalise commented on NEWS.md
Add sections for

+ New Features and Functions
+ Other Updates
+ Bug Fixes

2024-12-02 18:30 UTC, RaymondBalise commented on inst/gists/README.md
Add realtime check before overwriting existing README

2024-12-02 18:30 UTC, RaymondBalise commented on NEWS.md
> ++ Added `README.md` and `dated_progress_notes.md` templates to new projects
rUM provides a README template.  It will ask if you want to overwrite an existing README

2024-12-02 18:30 UTC, RaymondBalise commented on inst/gists/analysis_qmd_wo_example.qmd
move labels back to code {r }

2024-12-02 20:34 UTC, kyleGrealis commented on inst/gists/README.md
done in `R/make_project.R` 12.2.2024

2024-12-02 20:36 UTC, kyleGrealis commented on inst/gists/analysis_qmd_wo_example.qmd
done in `inst/gists/*.qmd` files -- 12.2.2024

2024-12-02 20:52 UTC, kyleGrealis commented on NEWS.md
done

2024-12-02 20:53 UTC, kyleGrealis commented on NEWS.md
> ++ Added custom.scss to non-package Quarto projects
done

2024-12-02 20:53 UTC, kyleGrealis commented on inst/old/analysis_1_0_2_9001.Rmd
removed 12.2.2024

2025-03-06 16:00 UTC, gabrielodom commented on R/make_project.R
> +  has_rproj <- length(list.files(path = path, pattern = "\\.Rproj$")) > 0
Why not use `file.exists()`?

2025-03-06 16:08 UTC, gabrielodom commented on R/make_project.R
This is a monster. When I've submitted to Bioconductor in the past (I know this is staying on CRAN, but bear with me), they flagged functions that were longer than 80 lines. Why? Functions grow exponentially harder to debug with each line added. In order to sustain this function long term, I STRONGLY recommend that this be broken up into multiple different functions and helper functions. The helper functions don't need to be exported, but they should be given their own documentation for future devs.

2025-03-06 16:27 UTC, gabrielodom commented on R/write_quarto.R
> +  if (is.null(filename)) stop('Invalid filename. Please input a value.')
this isn't checking if the filename is valid, only that it isn't empty. See this answer on checking valid file names per OS:
<https://stackoverflow.com/a/17263007/8366590>

2025-03-06 16:29 UTC, gabrielodom commented on R/write_quarto.R
Some of this stuff on valid file names should probably be moved to an independent helper function.

2025-03-06 16:32 UTC, gabrielodom commented on R/write_scss.R
> +}
missing new line at EoF

2025-03-06 16:35 UTC, gabrielodom commented on inst/gists/analysis_qmd_with_example.qmd
> +editor: source
bless you --  finally. I *hated* that the default was the visual editor

2025-03-06 16:45 UTC, gabrielodom commented on vignettes/O0_using_posit_cloud.Rmd
> +The other vignettes for `rUM` show you that it integrates with the RStudio IDE menus.  Unfortunately, on Posit.Cloud the **New Project** button does not know about `rUM`. So you will need to type a c
"its" not "it's"

2025-03-06 16:52 UTC, gabrielodom commented on vignettes/O4_make_a_package.Rmd
> +2. Set the license for your package.  **REMEMBER: Do share NOT sensitive data. Talk to the data privacy officer at your institution/organization before sharing any data.  Ask them for advice on setti
Add the following disclaimer: "The information presented is not legal advice, is not to be acted on as such, may not be current and is subject to change without notice."

2025-03-06 16:56 UTC, gabrielodom commented on rUM.Rproj
Well, I learned something new: https://forum.posit.co/t/use-for-projectid-in-rproj-file/196345

2025-03-06 16:57 UTC, gabrielodom approved these changes
I'm approving for now, but the next minor version needs to have the `make_project()` function completely factored. It's too much for one function.

2025-03-06 17:36 UTC, kyleGrealis commented on R/make_project.R
> +  has_rproj <- length(list.files(path = path, pattern = "\\.Rproj$")) > 0
though this method isn't ideal, it allows for regex syntax. using `file.exists()` to accomplish the same would be just as long:
```
file.exists(list.files(here::here(), pattern = "\\.Rproj$", full.names = TRUE)[1])
```
this would return TRUE/FALSE like the current set-up. I'm impartial and can add either or leave alone

2025-03-06 17:37 UTC, kyleGrealis commented on R/make_project.R
This is on my list of new implementations once this branch is approved & merged and the package is resubmitted to CRAN

2025-03-06 17:42 UTC, kyleGrealis commented on R/write_quarto.R
> +  if (is.null(filename)) stop('Invalid filename. Please input a value.')
Good point. I had `if (is.null(filename))...` because the function defaults to `filename = NULL`. Change to `stop("Missing filename. Please input a value.")` ??

2025-03-06 17:43 UTC, kyleGrealis commented on R/write_quarto.R
This would be a worthwhile addition, especially if we're planning to expand the package's functionality (CV/resume, dashboards, slides, etc.)

2025-03-06 17:47 UTC, kyleGrealis commented on R/write_scss.R
> +}
```
>> .display_reference_links <- function() {
+   links <- glue::glue(
+     "For more SCSS styling options, visit:\n",
+     "- [https://quarto.org/docs/output-formats/html-themes.html#customizing-themes\n](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)",
+     "- [https://quarto.org/docs/output-formats/html-themes-more.html\n](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)",
+     "- [https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss\n](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)"
+   )
+   message(links)
+ }
>> .display_reference_links()
For more SCSS styling options, visit:
- [https://quarto.org/docs/output-formats/html-themes.html#customizing-themes](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)
- [https://quarto.org/docs/output-formats/html-themes-more.html](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)
- [https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)
>>
```
I may be missing something on my end, but I don't get any messages/errors here.

2025-03-06 17:51 UTC, kyleGrealis commented on vignettes/O0_using_posit_cloud.Rmd
> +The other vignettes for `rUM` show you that it integrates with the RStudio IDE menus.  Unfortunately, on Posit.Cloud the **New Project** button does not know about `rUM`. So you will need to type a c
✅ done

2025-03-06 17:52 UTC, kyleGrealis commented on vignettes/O4_make_a_package.Rmd
> +2. Set the license for your package.  **REMEMBER: Do share NOT sensitive data. Talk to the data privacy officer at your institution/organization before sharing any data.  Ask them for advice on setti
✅ done

2025-03-06 17:59 UTC, gabrielodom commented on R/write_quarto.R
> +  if (is.null(filename)) stop('Invalid filename. Please input a value.')
I think so, unless you really want to get into what file names are valid on which OS

2025-03-06 18:00 UTC, gabrielodom commented on R/write_scss.R
> +}
I think it's a bug in the GitHub GUI. Ignore

2025-03-06 18:01 UTC, gabrielodom commented
@kyleGrealis can you see and resolve the conflicts in `NEWS.md`?

2025-03-06 18:02 UTC, kyleGrealis commented on R/write_quarto.R
> +  if (is.null(filename)) stop('Invalid filename. Please input a value.')
That's not a hole I'd like to fall into, but I'm here to serve :)

2025-03-06 18:06 UTC, kyleGrealis commented
> @kyleGrealis can you see and resolve the conflicts in `NEWS.md`?

@gabrielodom unfortunately I can't. how bad?

2025-03-06 18:09 UTC, kyleGrealis commented on rUM.Rproj
more the reason to just use Positron and not worry about .Rproj files 🙃 /s

2025-03-06 19:04 UTC, merged